### ISSUE TITLE
4xx codes

### ISSUE THREAD

**Issue by shortdudey123** [PagerDuty/devdocs#3]
Please add 401, 403, and 404 to the rest/errors page :)

**Comment by shortdudey123** [comment]
Also 408 and 499

**Comment by steverice** [comment]
499:

> Used in Nginx logs to indicate when the connection has been closed by client while the server is still processing its request, making server unable to send a status code back.[26]

Doesn't seem like clients need to know or care about that.

**Comment by shortdudey123** [comment]
hmm ok, the way the logs are structured it looks like 499 is being returned to clients

**Comment by kenrose** [comment]
Are we using GitHub issues for this repo? Who's responsible for implementing this?

**Comment by steverice** [comment]
Indeed. @shortdudey123 please create [JIRA tickets](https://pagerduty.atlassian.net/browse/API-51) for API issues.

**Comment by shortdudey123** [comment]
Followed up in original email to find out where to actually report stuff since everyone has a different answer

**Comment by steverice** [comment]
@shortdudey123 I don't think @kenrose and I were privy to said email, which is potentially where the confusion lies.
